import { Address, BigInt, Bytes, ethereum } from "@graphprotocol/graph-ts";
import { ChainlinkAggregator, MorphoChainlinkOracleData, Oracle, Position, LeverageManager, LendingAdapter, LeverageTokenState } from "../../generated/schema";
import { MORPHO_ORACLE_PRICE_SCALE_STRING, WAD_STRING } from "../constants";
import { LeverageManager as LeverageManagerContract } from "../../generated/LeverageManager/LeverageManager"

export function getPosition(
    user: Address,
    leverageToken: Address
): Position | null {
    const positionId = user
        .toHexString()
        .concat("-")
        .concat(leverageToken.toHexString());

    return Position.load(positionId);
}

/**
 * Mimics the logic of the MorphoChainlinkOracleV2.price() function
 * e.g. https://basescan.deth.net/address/0xFEa2D58cEfCb9fcb597723c6bAE66fFE4193aFE4
 */
export function calculateMorphoChainlinkPrice(
    morphoChainlinkOracleData: MorphoChainlinkOracleData
): BigInt {
    // TODO: If the vault is not the zero address, we need to fetch the asset amount from the vault
    const baseVaultAssets = BigInt.fromI32(1)
    const quoteVaultAssets = BigInt.fromI32(1)

    const baseAggregatorA = ChainlinkAggregator.load(morphoChainlinkOracleData.baseAggregatorA)

    const baseAggregatorB = morphoChainlinkOracleData.baseAggregatorB ? ChainlinkAggregator.load(morphoChainlinkOracleData.baseAggregatorB as Bytes) : null
    const quoteAggregatorA = morphoChainlinkOracleData.quoteAggregatorA ? ChainlinkAggregator.load(morphoChainlinkOracleData.quoteAggregatorA as Bytes) : null
    const quoteAggregatorB = morphoChainlinkOracleData.quoteAggregatorB ? ChainlinkAggregator.load(morphoChainlinkOracleData.quoteAggregatorB as Bytes) : null

    const basePriceA = baseAggregatorA ? baseAggregatorA.price : BigInt.fromI32(0)
    const basePriceB = baseAggregatorB ? baseAggregatorB.price : BigInt.fromI32(1)
    const quotePriceA = quoteAggregatorA ? quoteAggregatorA.price : BigInt.fromI32(1)
    const quotePriceB = quoteAggregatorB ? quoteAggregatorB.price : BigInt.fromI32(1)

    const numerator = morphoChainlinkOracleData.scaleFactor.times(baseVaultAssets).times(basePriceA).times(basePriceB)
    const denominator = quoteVaultAssets.times(quotePriceA).times(quotePriceB)

    return numerator.div(denominator)
}

export function convertToEquity(
    shares: BigInt,
    totalEquity: BigInt,
    totalShares: BigInt
): BigInt {
    return totalShares.isZero() ? BigInt.fromI32(0) : shares.times(totalEquity).div(totalShares)
}

export function convertCollateralToDebt(
    oracle: Oracle,
    collateral: BigInt
): BigInt {
    return collateral.times(oracle.price).div(BigInt.fromString(MORPHO_ORACLE_PRICE_SCALE_STRING))
}

export function convertDebtToCollateral(
    oracle: Oracle,
    debt: BigInt
): BigInt {
    const price = oracle.price
    const numerator = debt.times(BigInt.fromString(MORPHO_ORACLE_PRICE_SCALE_STRING));
    const remainder = price.isZero() ? BigInt.zero() : numerator.mod(price);
    const quotient = price.isZero() ? BigInt.zero() : numerator.div(price);
    return remainder.isZero() ? quotient : quotient.plus(BigInt.fromI32(1)); // Rounding up
}

/**
 * Updates leverage token state history for all leverage tokens that use the given oracle
 * @param leverageManager - The leverage manager entity
 * @param lendingAdapters - Array of lending adapters to process
 * @param oracle - The oracle entity to use for price conversions
 * @param block - The current block being processed
 */
export function updateLeverageTokenStatesForOracle(
    leverageManager: LeverageManager,
    lendingAdapters: LendingAdapter[],
    oracle: Oracle,
    block: ethereum.Block
): void {
    for (let j = 0; j < lendingAdapters.length; j++) {
        const lendingAdapter = lendingAdapters[j]
        const leverageTokens = lendingAdapter.leverageTokens.load()

        for (let k = 0; k < leverageTokens.length; k++) {
            const leverageToken = leverageTokens[k]
            const leverageManagerContract = LeverageManagerContract.bind(Address.fromBytes(leverageManager.id))

            const leverageTokenState = leverageManagerContract.getLeverageTokenState(
                Address.fromBytes(leverageToken.id)
            )

            const totalEquityInCollateral = convertDebtToCollateral(oracle, leverageTokenState.equity)
            const totalEquityInDebt = leverageTokenState.equity

            // The id for timeseries is autogenerated; even if we set it to a real value, it is silently overwritten
            const leverageTokenStateUpdate = new LeverageTokenState(0)
            leverageTokenStateUpdate.leverageToken = leverageToken.id
            leverageTokenStateUpdate.totalCollateral = leverageToken.totalCollateral
            leverageTokenStateUpdate.totalDebt = leverageTokenState.debt
            leverageTokenStateUpdate.totalEquityInCollateral = totalEquityInCollateral
            leverageTokenStateUpdate.totalEquityInDebt = totalEquityInDebt
            leverageTokenStateUpdate.collateralRatio = leverageTokenState.collateralRatio
            leverageTokenStateUpdate.totalSupply = leverageToken.totalSupply
            leverageTokenStateUpdate.equityPerTokenInCollateral = convertToEquity(
                BigInt.fromString(WAD_STRING),
                totalEquityInCollateral,
                leverageToken.totalSupply
            )
            leverageTokenStateUpdate.equityPerTokenInDebt = convertToEquity(
                BigInt.fromString(WAD_STRING),
                totalEquityInDebt,
                leverageToken.totalSupply
            )
            leverageTokenStateUpdate.timestamp = block.timestamp.toI64()
            leverageTokenStateUpdate.blockNumber = block.number
            leverageTokenStateUpdate.save()

            leverageToken.totalCollateralInDebt = leverageTokenState.collateralInDebtAsset
            leverageToken.collateralRatio = leverageTokenState.collateralRatio
            leverageToken.save()
        }
    }
}