import { Address, Bytes } from "@graphprotocol/graph-ts";
import { ChainlinkAggregator, LendingAdapter, LeverageManager, LeverageTokenEquity, MorphoChainlinkOracleData, OraclePrice } from "../generated/schema"
import { LEVERAGE_MANAGER_ADDRESS } from "./constants/addresses";
import { AnswerUpdated as AnswerUpdatedEvent } from "../generated/templates/ChainlinkAggregator/ChainlinkAggregator";
import { OracleType } from "./constants";
import { calculateMorphoChainlinkPrice, convertDebtToCollateral } from "./utils";
import { LeverageManager as LeverageManagerContract } from "../generated/LeverageManager/LeverageManager"

export function handleAnswerUpdated(event: AnswerUpdatedEvent): void {
  const chainlinkAggregator = ChainlinkAggregator.load(event.address)
  if (!chainlinkAggregator) {
    return
  }

  const leverageManager = LeverageManager.load(Address.fromHexString(LEVERAGE_MANAGER_ADDRESS))
  if (!leverageManager) {
    return
  }

  chainlinkAggregator.price = event.params.current
  chainlinkAggregator.save()

  // Update prices on oracles using this ChainlinkAggregator
  const oracles = leverageManager._oracles.load()
  for (let i = 0; i < oracles.length; i++) {
    const oracle = oracles[i]

    if (oracle.type === OracleType.MORPHO_CHAINLINK) {
        const morphoChainlinkOracleDataId = oracle.morphoChainlinkOracleData
        if (morphoChainlinkOracleDataId === null) {
            return
        }

        const morphoChainlinkOracleData = MorphoChainlinkOracleData.load(morphoChainlinkOracleDataId)
        if (morphoChainlinkOracleData === null) {
            return
        }

        if (
            morphoChainlinkOracleData.baseAggregatorA.equals(chainlinkAggregator.id) ||
            (morphoChainlinkOracleData.baseAggregatorB !== null && (morphoChainlinkOracleData.baseAggregatorB as Bytes).equals(chainlinkAggregator.id)) ||
            (morphoChainlinkOracleData.quoteAggregatorA !== null && (morphoChainlinkOracleData.quoteAggregatorA as Bytes).equals(chainlinkAggregator.id)) ||
            (morphoChainlinkOracleData.quoteAggregatorB !== null && (morphoChainlinkOracleData.quoteAggregatorB as Bytes).equals(chainlinkAggregator.id))
        ) {
            const newOraclePrice = calculateMorphoChainlinkPrice(morphoChainlinkOracleData)

            oracle.price = newOraclePrice
            oracle.save()

            const priceUpdate = new OraclePrice(0)
            priceUpdate.oracle = oracle.id
            priceUpdate.price = newOraclePrice
            priceUpdate.timestamp = event.block.timestamp.toI64()
            priceUpdate.save()

            // Update equity for all LeverageTokens that use this oracle
            const leverageTokens = leverageManager.leverageTokens.load()
            const leverageManagerContract = LeverageManagerContract.bind(Address.fromBytes(leverageManager.id))
            for (let j = 0; j < leverageTokens.length; j++) {
                const leverageToken = leverageTokens[j]
                const lendingAdapter = LendingAdapter.load(leverageToken.lendingAdapter)

                if (lendingAdapter === null) {
                    continue
                }

                if (lendingAdapter.oracle.equals(oracle.id)) {
                    // We have to fetch the current equity on chain due to interest accrual potentially changing the current
                    // amount of equity
                    const leverageTokenState = leverageManagerContract.getLeverageTokenState(
                        Address.fromBytes(leverageToken.id)
                    )

                    // The id for timeseries is autogenerated; even if we set it to a real value, it is silently overwritten
                    const leverageTokenEquityUpdate = new LeverageTokenEquity(0)
                    leverageTokenEquityUpdate.leverageToken = leverageToken.id
                    leverageTokenEquityUpdate.totalCollateral = leverageToken.totalCollateral
                    leverageTokenEquityUpdate.totalDebt = leverageTokenState.debt
                    leverageTokenEquityUpdate.totalEquityInCollateral = convertDebtToCollateral(
                        oracle,
                        leverageTokenState.equity
                    )
                    leverageTokenEquityUpdate.totalEquityInDebt = leverageTokenState.equity
                    leverageTokenEquityUpdate.collateralRatio = leverageTokenState.collateralRatio
                    leverageTokenEquityUpdate.timestamp = event.block.timestamp.toI64()
                    leverageTokenEquityUpdate.blockNumber = event.block.number
                    leverageTokenEquityUpdate.save()

                    leverageToken.totalCollateralInDebt = leverageTokenState.collateralInDebtAsset
                    leverageToken.collateralRatio = leverageTokenState.collateralRatio
                    leverageToken.save()
                }
            }
        }
    }
  }
}