import { Address, Bytes } from "@graphprotocol/graph-ts";
import { ChainlinkAggregator, LendingAdapter, LeverageManager, LeverageTokenState, MorphoChainlinkOracleData, OraclePrice } from "../generated/schema"
import { LEVERAGE_MANAGER_ADDRESS } from "./constants/addresses";
import { AnswerUpdated as AnswerUpdatedEvent } from "../generated/templates/ChainlinkAggregator/ChainlinkAggregator";
import { OracleType } from "./constants";
import { calculateMorphoChainlinkPrice, convertDebtToCollateral } from "./utils";
import { LeverageManager as LeverageManagerContract } from "../generated/LeverageManager/LeverageManager"

export function handleAnswerUpdated(event: AnswerUpdatedEvent): void {
  const chainlinkAggregator = ChainlinkAggregator.load(event.address)
  if (!chainlinkAggregator) {
    return
  }

  const leverageManager = LeverageManager.load(Address.fromHexString(LEVERAGE_MANAGER_ADDRESS))
  if (!leverageManager) {
    return
  }

  chainlinkAggregator.price = event.params.current
  chainlinkAggregator.save()

  // Update prices on oracles using this ChainlinkAggregator
  const oracles = leverageManager._oracles.load()
  for (let i = 0; i < oracles.length; i++) {
    const oracle = oracles[i]

    if (oracle.type === OracleType.MORPHO_CHAINLINK) {
        const morphoChainlinkOracleDataId = oracle.morphoChainlinkOracleData
        if (morphoChainlinkOracleDataId === null) {
            return
        }

        const morphoChainlinkOracleData = MorphoChainlinkOracleData.load(morphoChainlinkOracleDataId)
        if (morphoChainlinkOracleData === null) {
            return
        }

        if (
            morphoChainlinkOracleData.baseAggregatorA.equals(chainlinkAggregator.id) ||
            (morphoChainlinkOracleData.baseAggregatorB !== null && (morphoChainlinkOracleData.baseAggregatorB as Bytes).equals(chainlinkAggregator.id)) ||
            (morphoChainlinkOracleData.quoteAggregatorA !== null && (morphoChainlinkOracleData.quoteAggregatorA as Bytes).equals(chainlinkAggregator.id)) ||
            (morphoChainlinkOracleData.quoteAggregatorB !== null && (morphoChainlinkOracleData.quoteAggregatorB as Bytes).equals(chainlinkAggregator.id))
        ) {
            const newOraclePrice = calculateMorphoChainlinkPrice(morphoChainlinkOracleData)

            oracle.price = newOraclePrice
            oracle.save()

            const priceUpdate = new OraclePrice(0)
            priceUpdate.oracle = oracle.id
            priceUpdate.price = newOraclePrice
            priceUpdate.timestamp = event.block.timestamp.toI64()
            priceUpdate.save()

            // Update state history for all LeverageTokens that use this oracle
            const lendingAdapters = oracle.lendingAdapters.load()
            for (let j = 0; j < lendingAdapters.length; j++) {
                const lendingAdapter = lendingAdapters[j]
                const leverageTokens = lendingAdapter.leverageTokens.load()

                for (let k = 0; k < leverageTokens.length; k++) {
                    const leverageToken = leverageTokens[k]
                    const leverageManagerContract = LeverageManagerContract.bind(Address.fromBytes(leverageManager.id))

                    const leverageTokenState = leverageManagerContract.getLeverageTokenState(
                        Address.fromBytes(leverageToken.id)
                    )

                    // The id for timeseries is autogenerated; even if we set it to a real value, it is silently overwritten
                    const leverageTokenStateUpdate = new LeverageTokenState(0)
                    leverageTokenStateUpdate.leverageToken = leverageToken.id
                    leverageTokenStateUpdate.totalCollateral = leverageToken.totalCollateral
                    leverageTokenStateUpdate.totalDebt = leverageTokenState.debt
                    leverageTokenStateUpdate.totalEquityInCollateral = convertDebtToCollateral(
                        oracle,
                        leverageTokenState.equity
                    )
                    leverageTokenStateUpdate.totalEquityInDebt = leverageTokenState.equity
                    leverageTokenStateUpdate.collateralRatio = leverageTokenState.collateralRatio
                    leverageTokenStateUpdate.timestamp = event.block.timestamp.toI64()
                    leverageTokenStateUpdate.blockNumber = event.block.number
                    leverageTokenStateUpdate.save()

                    leverageToken.totalCollateralInDebt = leverageTokenState.collateralInDebtAsset
                    leverageToken.collateralRatio = leverageTokenState.collateralRatio
                    leverageToken.save()
                }
            }
        }
    }
  }
}