import { Address, BigInt } from "@graphprotocol/graph-ts"
import { LeverageManager, LeverageToken, Position, PositionEquity, User } from "../generated/schema"
import {
  Transfer as TransferEvent,
} from "../generated/templates/LeverageToken/LeverageToken"
import { getPositionStub } from "./stubs"

export function handleTransfer(event: TransferEvent): void {
  const leverageToken = LeverageToken.load(event.address)
  if (!leverageToken) {
    return
  }

  const leverageManager = LeverageManager.load(leverageToken.leverageManager)
  if (!leverageManager) {
    return
  }

  const isTransferEvent = isTransfer(event)
  const equityInCollateralDelta = isTransferEvent ? calculateEquityForShares(event.params.value, leverageToken.totalEquityInCollateral, leverageToken.totalSupply) : BigInt.zero()
  const equityInDebtDelta = isTransferEvent ? calculateEquityForShares(event.params.value, leverageToken.totalEquityInDebt, leverageToken.totalSupply) : BigInt.zero()

  if (event.params.from.equals(Address.zero())) {
    leverageToken.totalSupply = leverageToken.totalSupply.plus(event.params.value)
  } else if (event.params.to.equals(Address.zero())) {
    leverageToken.totalSupply = leverageToken.totalSupply.minus(event.params.value)
  }

  if (event.params.from.notEqual(Address.zero())) {
    const fromPositionId = event.params.from.toHexString().concat("-").concat(leverageToken.id.toHexString())
    let fromPosition = Position.load(fromPositionId)
    if (!fromPosition) {
      return
    }

    if (isTransferEvent) {
      updatePositionEquityAndBalance(event, fromPosition, equityInCollateralDelta, equityInDebtDelta, event.params.value, false)
    }

    if (fromPosition.balance.isZero()) {
      leverageToken.totalHolders = leverageToken.totalHolders.minus(BigInt.fromI32(1))
      leverageManager.totalHolders = leverageManager.totalHolders.minus(BigInt.fromI32(1))
    }
  }

  if (event.params.to.notEqual(Address.zero())) {
    let user = User.load(event.params.to)
    if (!user) {
      user = new User(event.params.to)
      user.save()
    }

    const toPositionId = event.params.to.toHexString().concat("-").concat(leverageToken.id.toHexString())
    let toPosition = Position.load(toPositionId)
    if (!toPosition) {
      toPosition = getPositionStub(Address.fromBytes(user.id), Address.fromBytes(leverageToken.id))
    }

    if (toPosition.balance.isZero() && event.params.value.gt(BigInt.zero())) {
      leverageToken.totalHolders = leverageToken.totalHolders.plus(BigInt.fromI32(1))
      leverageManager.totalHolders = leverageManager.totalHolders.plus(BigInt.fromI32(1))
    }


    if (isTransferEvent) {
      updatePositionEquityAndBalance(event, toPosition, equityInCollateralDelta, equityInDebtDelta, event.params.value, true)
    }
  }

  leverageToken.save()
  leverageManager.save()
}

function calculateEquityForShares(shares: BigInt, totalEquity: BigInt, totalSupply: BigInt): BigInt {
  return shares.times(totalEquity).div(totalSupply);
}

function isTransfer(event: TransferEvent): boolean {
  return event.params.from.notEqual(Address.zero()) && event.params.to.notEqual(Address.zero());
}

function updatePositionEquityAndBalance(event: TransferEvent, position: Position, equityInCollateralDelta: BigInt, equityInDebtDelta: BigInt, balanceDelta: BigInt, isIncrease: boolean): void {
  if (isIncrease) {
    position.equityInCollateral = position.equityInCollateral.plus(equityInCollateralDelta);
    position.equityInDebt = position.equityInDebt.plus(equityInDebtDelta);
    position.balance = position.balance.plus(balanceDelta);
  } else {
    position.equityInCollateral = position.equityInCollateral.minus(equityInCollateralDelta);
    position.equityInDebt = position.equityInDebt.minus(equityInDebtDelta);
    position.balance = position.balance.minus(balanceDelta);
  }
  position.save();

  // The id for timeseries is autogenerated; even if we set it to a real value, it is silently overwritten
  const positionEquityUpdate = new PositionEquity(0);
  positionEquityUpdate.position = position.id;
  positionEquityUpdate.equityInCollateral = position.equityInCollateral;
  positionEquityUpdate.equityInDebt = position.equityInDebt;
  positionEquityUpdate.timestamp = event.block.timestamp.toI64();
  positionEquityUpdate.blockNumber = event.block.number;
  positionEquityUpdate.save();
}