import { Address, BigInt, Bytes } from "@graphprotocol/graph-ts"
import { LeverageManager as LeverageManagerContract } from "../generated/RlpPriceStorage/LeverageManager"
import { PriceSet as PriceSetEvent } from "../generated/RlpPriceStorage/RlpPriceStorage"
import { ChainlinkAggregator, LeverageTokenState, MorphoChainlinkOracleData, Oracle, OraclePrice } from "../generated/schema"
import { MORPHO_CHAINLINK_ORACLE_V2_RLP_USDC_ADDRESS } from "./constants/addresses"
import { calculateMorphoChainlinkPrice, convertDebtToCollateral, convertToEquity } from "./utils"
import { WAD_STRING } from "./constants"

export function handlePriceSet(event: PriceSetEvent): void {
    let rlpUsdcOracle = Oracle.load(Address.fromString(MORPHO_CHAINLINK_ORACLE_V2_RLP_USDC_ADDRESS))
    if (!rlpUsdcOracle) {
        return;
    }

    const morphoChainlinkOracleData = MorphoChainlinkOracleData.load(rlpUsdcOracle.morphoChainlinkOracleData as Bytes);
    if (!morphoChainlinkOracleData) {
        return;
    }

    const feed = ChainlinkAggregator.load(morphoChainlinkOracleData.baseAggregatorA)
    if (!feed) {
        return;
    }

    // Mimicking scaling down performed by the oracle's BASE_FEED_1 contract (RlpPriceAggregatorV3Interface)
    // https://etherscan.io/address/0xAdb2c15Fde49D1A4294740aCb650de94184E66b2#code
    feed.price = event.params.price.div(BigInt.fromI32(10).pow(10))
    feed.save();

    rlpUsdcOracle.price = calculateMorphoChainlinkPrice(morphoChainlinkOracleData)
    rlpUsdcOracle.save()

    const priceUpdate = new OraclePrice(0)
    priceUpdate.oracle = rlpUsdcOracle.id
    priceUpdate.price = rlpUsdcOracle.price
    priceUpdate.timestamp = event.block.timestamp.toI64()
    priceUpdate.save()

    // Update state history for all LeverageTokens that use this oracle
    const lendingAdapters = rlpUsdcOracle.lendingAdapters.load()
    for (let j = 0; j < lendingAdapters.length; j++) {
        const lendingAdapter = lendingAdapters[j]
        const leverageTokens = lendingAdapter.leverageTokens.load()

        for (let k = 0; k < leverageTokens.length; k++) {
            const leverageToken = leverageTokens[k]
            const leverageManagerContract = LeverageManagerContract.bind(Address.fromBytes(leverageToken.leverageManager))

            const leverageTokenState = leverageManagerContract.getLeverageTokenState(
                Address.fromBytes(leverageToken.id)
            )

            const totalEquityInCollateral = convertDebtToCollateral(rlpUsdcOracle, leverageTokenState.equity)
            const totalEquityInDebt = leverageTokenState.equity

            // The id for timeseries is autogenerated; even if we set it to a real value, it is silently overwritten
            const leverageTokenStateUpdate = new LeverageTokenState(0)
            leverageTokenStateUpdate.leverageToken = leverageToken.id
            leverageTokenStateUpdate.totalCollateral = leverageToken.totalCollateral
            leverageTokenStateUpdate.totalDebt = leverageTokenState.debt
            leverageTokenStateUpdate.totalEquityInCollateral = totalEquityInCollateral
            leverageTokenStateUpdate.totalEquityInDebt = totalEquityInDebt
            leverageTokenStateUpdate.collateralRatio = leverageTokenState.collateralRatio
            leverageTokenStateUpdate.totalSupply = leverageToken.totalSupply
            leverageTokenStateUpdate.equityPerTokenInCollateral = convertToEquity(
                BigInt.fromString(WAD_STRING),
                totalEquityInCollateral,
                leverageToken.totalSupply
            )
            leverageTokenStateUpdate.equityPerTokenInDebt = convertToEquity(
                BigInt.fromString(WAD_STRING),
                totalEquityInDebt,
                leverageToken.totalSupply
            )
            leverageTokenStateUpdate.timestamp = event.block.timestamp.toI64()
            leverageTokenStateUpdate.blockNumber = event.block.number
            leverageTokenStateUpdate.save()

            leverageToken.totalCollateralInDebt = leverageTokenState.collateralInDebtAsset
            leverageToken.collateralRatio = leverageTokenState.collateralRatio
            leverageToken.save()
        }
    }
}